### ISSUE TITLE
Support for Silhouette Portrait 8x12 cutting mat

### ISSUE THREAD

**Issue by DASPRiD** [jnweiger/inkscape-silhouette#164]
At the moment, only the two Cameo cutting mats are supported.
Should there be an additional option for the Silhouette 8x12 cutting mat?

**Comment by t0b3** [comment]
@DASPRiD if you feel the need just contribute a PR...

**Comment by DASPRiD** [comment]
Looking at the `CAMEO_MATS` dict, I'm not sure what the first parameter should be for the 8x12 cutting mat:

https://github.com/fablabnbg/inkscape-silhouette/blob/d75540e995b37a6051e283326cd988cec62baaa7/silhouette/Graphtec.py#L117-L123

Any guide on how to figure out which value to set for that?

**Comment by gwhitney** [comment]
I believe all of the known values were obtained by setting the corresponding mat in the Silhouette app and sniffing the USB communication for the "n" in the "TGn" command issued to the cutter. At least, that's how I found the '8' and '9' for the 15x15 and 24x24 mats. I don't know of another method for finding these numbers...

**Comment by dolorosus** [comment]
I took a usbdump with wireshark, but could not find any TG command. What am i doing wrong?
[silhouette 8x12 cut.zip](https://github.com/fablabnbg/inkscape-silhouette/files/8340121/silhouette.8x12.cut.zip)

**Comment by gwhitney** [comment]
Hmm, I am sorry to say I don't know. It is in my limited experience just before the FN0 command, which I do see in your dump.So there is definitely GPGL being sent in that dump.

I guess all I can think of is try doing multiple dumps on identical cut runs except that you tell the software you have a different mat each time (even if you are lying, I don't actually own a 15x15 mat) , and then try to line up the common parts of the dumps (they should be close to identical) and then try to see where they differ... conceivably the 8x12 mat is the default for a portrait so it doesn't send any command? That's why it could be helpful to just compare the dumps from different mat settings. Other than that, a more experienced person than me would have to weigh in.

**Comment by dolorosus** [comment]
Thanks for looking into it and pointing me to GPGL. I wasn't aware that 8x12 is the default. I agree that the TG command seems to be missing due to this fact. 
Many thanks

**Comment by gwhitney** [comment]
Oh, I don't _know_ whether 8x12 is the default for a Portrait. That was a wild guess because I have no idea why the TG command is missing; it definitely showed up in the dumps I did with a Cameo 4 Pro (I also think I used some other tool than wireshark, can't recall, it's been a while). Best of luck and let us know how it goes...

**Comment by DASPRiD** [comment]
I'd assume "no mat" to be the default. I wonder what is send without a mat instead.

**Comment by dolorosus** [comment]
AFAIK 8x12 is the smallest available mat and the Silhoutte Portrait can use a maximum of 8 in width. So I guess it doesn't matter if the SP is used with or without a matte.

**Comment by simon-budig** [comment]
I am looking at some logs here and I am pretty certain that the 8x12 mat is "TG3" (tested with a portrait3)

**Comment by simon-budig** [comment]
I have some initialization sequences for various settings on a Portrait 3

Setting "no cutting mat", Document Format "Letter portrait"

> TG0 | FN0 | TB50,0 | \30,0 | Z5088,4120 | 
> FX22 | !3 | FC18 | FE0,0 | 
> FF1,1,0 | FF1,1,0 | FX22 | 
> FC18 | TF1,1 | 


Setting "portrait cutting mat", Document Format "Letter portrait"

> TG3 | FN0 | TB50,0 | \30,0 | Z5558,4120 | 
> FX10 | !4 | FC18 | FE0,0 | 
> FF1,1,0 | FF1,1,0 | FX10 | 
> FC18 | TF1,1 | 


Setting "portrait cutting mat", Document Format "A4 portrait"

> TG3 | FN0 | TB50,0 | \30,0 | Z5910,4120 | 
> FX10 | !4 | FC18 | FE0,0 | 
> FF1,1,0 | FF1,1,0 | FX10 | 
> FC18 | TF2,1 | 


Setting "portrait cutting mat", Document Format "A5 portrait"

> TG3 | FN0 | TB50,0 | \30,56 | Z4170,2956 | 
> FX10 | !4 | FC18 | FE0,0 | 
> FF1,1,0 | FF1,1,0 | FX10 | 
> FC18 | TF3,1 | 

So, yeah. TG3 is the portrait cutting mat, "TG0" is "no cutting mat". (FWIW: I also changed the auto-cutter depth here to identify the initialization-sequences)

Unfortunately I seem to be unable to attach the json dump from wireshark, github rejects them with "something went really wrong", so I dunno...
