### ISSUE TITLE
DeprecationWarning

### ISSUE THREAD

**Issue by mfraser** [jnweiger/inkscape-silhouette#207]
Using inkscape-silhouette 1.26 with Inkscape 1.2.1, I receive this depreciation warning:

/usr/share/inkscape/extensions/sendto_silhouette.py:641: DeprecationWarning: inkex.deprecated.main.transform_mul -> Use @ operator instead
  transform = Transform(self.docTransform) * transform
/usr/share/inkscape/extensions/sendto_silhouette.py:642: DeprecationWarning: inkex.deprecated.main.transform_mul -> Use @ operator instead
  transform = Transform(extra_transform) * transform

**Comment by t0b3** [comment]
thank you for this issue

... which is why I fixed it in main. if you are eager to get rid of this warning you may try latest main branch.
https://github.com/fablabnbg/inkscape-silhouette/blob/0c8942bffdd2d30136bbad41fdb4e50553ce4dec/sendto_silhouette.py#L511-L514

I hope this solves your issues. Feel free to report back in case you find something additional...
