### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by pseudomonas** [jnweiger/inkscape-silhouette#212]
Ubuntu 20.04; Python 3.8.10; Inkscape 1.2 (1:1.2.1+202207142221+cd75a1ee6d); Silhouette Cameo 4; latest inkscape-silhouette

"Inkscape has received additional data from the script:"
```
sendto_silhouette.py:641: DeprecationWarning: inkex.deprecated.main.transform_mul -> Use @ operator instead
  transform = Transform(self.docTransform) * transform
sendto_silhouette.py:642: DeprecationWarning: inkex.deprecated.main.transform_mul -> Use @ operator instead
  transform = Transform(extra_transform) * transform

```

**Comment by Zendrick42** [comment]
I am seeing the same message, but it also has the following lines, since I installed matplotlib for the preview:

/home/[REDACTED]/.local/lib/python3.8/site-packages/matplotlib/backends/_backend_gtk.py:146: DeprecationWarning: Gtk.Window.set_wmclass is deprecated
  self.window.set_wmclass("matplotlib", "Matplotlib")

**Comment by t0b3** [comment]
@pseudomonas thanks for reporting. this has been adressed by 3a66e635c0d8bb369ebde697b4caa654853f2ecd.

@Zendrick42 this looks like a matplotlib issue. you may upgrade your matplotlib installation. feel free to come back and open a new issue in case ...
